### ISSUE TITLE
Can't build libPNG

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/FFmpegKit#11]
Hi, 

i cannot build LibPNG using the script, any idea, neither on M1 or on Intel. Any idea ?

ld: building for 'macCatalyst', but linking in object file (Project/FFmpegKit/.Script/png/maccatalyst/scratch/arm64/CMakeFiles/png_shared.dir/arm/filter_neon.S.o) built for 'macOS'

**Comment by kingslay** [comment]
LibPNG 不支持最新cmake。需要等LibPNG新版本升级，已经有mr，下个版本的LibPNG应该就可以了。

**Comment by kingslay** [comment]
你这个是一定要有macCatalyst的吗？如果不需要macCatalyst，是可以根据platforms来进行配置你想要的系统。

**Comment by kingslay** [comment]
如果你有需要的话，我也可以本地帮你编译好。然后上传到这个库的mpv分支
