### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by romanyczn1** [kingslay/FFmpegKit#13]
Hi;)
Can you please provide new lib version, 6.1.1?

**Comment by kingslay** [comment]
我看FFmpeg现在只有6.1版本，还没出6.1.1

**Comment by romanyczn1** [comment]
> 我看FFmpeg现在只有6.1版本，还没出6.1.1

Is version 6.1 stable and i can use it for now?
I'm worried that there may be important changes in the latest commits

**Comment by kingslay** [comment]
目前没有人反馈有问题。

**Comment by romanyczn1** [comment]
> 目前没有人反馈有问题。

Okay, thanks!
