### ISSUE TITLE
ffmpeg升级到6.1后，部分直播无法播放

### ISSUE THREAD

**Issue by Kimentanm** [kingslay/FFmpegKit#16]
test url: http://live.aptvapp.com/test.php
降级之后可播放

这个php代理如果加上了： header('Content-Type: application/vnd.apple.mpegurl');
就可以播放了，在6.1之前没问题

**Comment by kingslay** [comment]
用6.1版本的ffplay也会有这个问题吗

**Comment by Kimentanm** [comment]
我这homebrew安装的ffmpeg最高就是6.0 😂

我用最新的TracyPlayer试了，确实是不能播放
6.0的ffplay没问题，可以播放

**Comment by kingslay** [comment]
可以到官网自己下载ffplay。就会有6.1了

**Comment by Kimentanm** [comment]
下载ffplay 6.1 也是无法播放 错误提示信息如下
```bash
Not detecting m3u8/hls with non standard extension and non standard mime type
    Last message repeated 1 times
http://live.aptvapp.com/test.php: Invalid data found when processing input
```

**Comment by kingslay** [comment]
好的。那你可以给ffmpeg提一下这个bug。我也试下看我这边是否有方案可以绕过这个错误。

**Comment by kingslay** [comment]
@Kimentanm 现在ffmpegkit升级到7.0了。你看下还会不会有这个问题。

**Comment by Kimentanm** [comment]
好的，我来试试
