### ISSUE TITLE
苹果芯片MacBook brew环境问题

### ISSUE THREAD

**Issue by loveq369** [kingslay/FFmpegKit#2]
苹果芯片 brew安装在 /opt/homebrew/bin/brew，检测不到。

**Comment by kingslay** [comment]
你可以改下 看下怎么样才可以 我这边没有m芯片的macbook 所以无法调试

**Comment by FantasyKingdom** [comment]
> 苹果芯片 brew安装在 /opt/homebrew/bin/brew，检测不到。

我也遇到这个问题。我在shell窗口中执行“which brew”是能找到的，但是在Utility的shell中怎么都找不到这个命令。你有解决这个问题吗？

**Comment by FantasyKingdom** [comment]
> 苹果芯片 brew安装在 /opt/homebrew/bin/brew，检测不到。
@loveq369 
我也遇到这个问题。我在shell窗口中执行“which brew”是能找到的，但是在Utility的shell中怎么都找不到这个命令。你有解决这个问题吗？

**Comment by FantasyKingdom** [comment]
@FantasyKingdom @loveq369  我已经解决了，Process的environment中，path里面加上: /opt/homebrew/bin这个路径就行，["PATH"] = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin"
