### ISSUE TITLE
PLS: Update ffmpeg to 6.1 with vulcan support

### ISSUE THREAD

**Issue by Alanko5** [kingslay/FFmpegKit#2]
Ffmpeg now support vulcan decoding for more codecs.

**Comment by kingslay** [comment]
6.1版本还没正式发出吧

**Comment by kingslay** [comment]
我查了下 [Vulkan](https://github.com/SaschaWillems/Vulkan) 好像只支持iOS macOS，不支持tvOS

**Comment by kingslay** [comment]
6.1发出来了。我看了。解码方面是 vulkan decode hwaccel, supporting H264, HEVC and AV1。 目前这几个格式本来就是走硬解了。所以还可以不用接入vulkan。
