### ISSUE TITLE
如何支持 nfs?

### ISSUE THREAD

**Issue by FaiChou** [kingslay/FFmpegKit#23]
看到此库已经将编译 nfs 的脚本加进去了。但是不知道 ffmpeg 如何开启 nfs 的支持，就像 [libsmbclient](https://ffmpeg.org/ffmpeg-protocols.html#libsmbclient) 的支持，ffmpeg 文档中并没有看到有 nfs 协议的支持。

**Comment by kingslay** [comment]
目前我也还是找不到直接播放nfs链接的方式。我试了把nfs的文件拷贝到本地来进行播放。是可以的，但是这样的方式会导致本地的磁盘空间紧张。特别是对于4k的视频。我想到的另一个方式就是利用avio_alloc_context来自定义协议。

**Comment by kingslay** [comment]
目前lgpl版本支持通过自定义协议的方式来支持nfs了。
