### ISSUE TITLE
Is it possible to receive and show UDP live stream using FFPlay in Swiftui?

### ISSUE THREAD

**Issue by uguraltinsoy** [kingslay/FFmpegKit#24]
Is it possible to receive and show UDP live stream using FFPlay in Swiftui?

**Comment by kingslay** [comment]
FFPlay是一个命令行应用程序，所以无法在SwiftUI上使用。你可以用我的另一个项目KSPlayer。里面的KSVideoPlayerView就是用SwiftUI来实现的。
