### ISSUE TITLE
How to use custom FFMPEG 6.1 code?

### ISSUE THREAD

**Issue by ragotiteb** [kingslay/FFmpegKit#25]
Hi

We have a forked version of FFMPEG 6.1 with a couple of custom filters and functionalities. We would like to use that version with KSPlayer and FFMPEGKit. Could you point to what steps do you recommend to take to have that FFMPEG version working in this stack? Thanks in advance.

**Comment by kingslay** [comment]
你可以直接改下代码里面的ffmpeg的git地址和分支。然后重新build下就可以了
