### ISSUE TITLE
编译过程中报错

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/FFmpegKit#29]
编译libsmbclient中途报这个错误，我用的是M1芯片的MacBook
--without-ldb-lmdb implied as this host is not 64-bit
error: Error Domain=fail Code=2 "(null)"

**Comment by kingslay** [comment]
我这边是可以的。你是在编译那一端的libsmbclient报错的，iOS还是tvos

**Comment by FantasyKingdom** [comment]
编译的是ios端。platforms=ios

**Comment by kingslay** [comment]
我试了下，是不会报错的。你需要检查你的环境。看下是那边有问题
