### ISSUE TITLE
请问如何为 xros 编译 libsrt 和 openssl？

### ISSUE THREAD

**Issue by yeahohooh** [kingslay/FFmpegKit#3]
我现在能为 xrosSimulator 成功编译 openssl，但是 xros 却始终搞不定，请问大神是如何编译的？感谢感谢

**Comment by yeahohooh** [comment]
Xcode 15.0 beta 5

**Comment by kingslay** [comment]
我这边试了xros 是可以编译成功的，你编译报什么错呢

**Comment by yeahohooh** [comment]
我这已经解决了，谢谢啦
