### ISSUE TITLE
libzvbi missing for macOS Catalyst

### ISSUE THREAD

**Issue by nihalahmed** [kingslay/FFmpegKit#31]
libzvbi.xcframework does not contain a slice for ios-arm64_x86_64-maccatalyst causing the build to fail when using Cocoapods.

**Comment by kingslay** [comment]
你可以先用spm。就不会有这个问题

**Comment by nihalahmed** [comment]
I need to use Cocoapods due to a conflict with libmpv and another pod that causes the other pod to fail.
Are you able to fix the Cocoapods issue?

**Comment by kingslay** [comment]
我看了Cocoapods 好像是不支持的macCatalyst。所以无法区分macOS和macCatalyst。 还有一个方式是让libzvbi在macCatalyst上可以编译成功

**Comment by nihalahmed** [comment]
What is the other way to compile other than SPM?

**Comment by kingslay** [comment]
还有一种方式，你自己编译没有libzvbi的ffmpeg。然后自己改下podspec

**Comment by nihalahmed** [comment]
Oh okay, thanks.
