### ISSUE TITLE
如何在不播放的情况下,获取视频的总时间长度? 目前貌似没有 api 可以获取?

### ISSUE THREAD

**Issue by freddiezhao** [kingslay/FFmpegKit#33]
您好,如何在不播放的情况下,获取视频的总时间长度? 目前貌似没有 api 可以获取?

**Comment by kingslay** [comment]
是可以的。你可以去看我的另外一个项目KSPlayer。或是执行命令swift run ffmpeg 就能查看视频的总时间

**Comment by freddiezhao** [comment]
ksplayer我看过了，好像没看到在没有播放的情况下能够获取时长的API呢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月23日 22:16 |
| 收件人 | kingslay/FFmpegKit ***@***.***> |
| 抄送人 | william ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [kingslay/FFmpegKit] 如何在不播放的情况下,获取视频的总时间长度? 目前貌似没有 api 可以获取? (Issue #33) |

是可以的。你可以去看我的另外一个项目KSPlayer。或是执行命令swift run ffmpeg 就能查看视频的总时间
