### ISSUE TITLE
smb 协议还是无法使用吗？还是需要额外什么配置吗？

### ISSUE THREAD

**Issue by HelloBoLun** [kingslay/FFmpegKit#34]

**Comment by kingslay** [comment]
可以的。你可以在命令行运行下swift run ffplay smb://xxx
但是这个使用的是libsmbclient。 libsmbclient是gpl协议的，整个app是需要开源才可以的。

**Comment by HelloBoLun** [comment]
@kingslay 你好 我的描述不够清晰 ，我的意思是根据编译生成的ffmpeg 相关库调用 var result = avformat_open_input(&self.formatCtx, urlString, nil, &avOptions)
这样好像无法进行smb数据解码
