### ISSUE TITLE
tvOS version issue

### ISSUE THREAD

**Issue by frestobile** [kingslay/FFmpegKit#37]
I am getting some issues for tvOS, when I try to use ffmpeg with this repo. 
Could you check the issues?   I am getting following error 

.../path/ffmpeg.kit/ffmpeg (no such file.)

**Comment by kingslay** [comment]
你是如何使用ffmpeg的呢？

**Comment by frestobile** [comment]
I have integrated this repo with swift package manager.
I am making a simple tvOS app and I need to encode the audio codec AC-4 with ffmpeg.  
But old version ffmpeg doesn't support it. 
![Screenshot 2024-10-19 213252](https://github.com/user-attachments/assets/64e8e2a3-65f0-4b04-9885-386a12fb3345)
![Screenshot 2024-10-19 213446](https://github.com/user-attachments/assets/a6679bcf-309f-4fd3-a3c6-0da7f0721e35)

**Comment by kingslay** [comment]
gpl版本是没有这个功能的，我在lgpl版本增加了调用ffmpg的功能了。

**Comment by frestobile** [comment]
How can I resolve the issue I have shown from the screenshot?

**Comment by kingslay** [comment]
你要申请lgpl授权，才能访问lgpl分支的代码。

**Comment by frestobile** [comment]
Please guide me to access to lgpl point.  I hope you help me, please.

**Comment by kingslay** [comment]
这个仓库一般是跟https://github.com/kingslay/KSPlayer/ 一起使用的，所以是一起授权lgpl。你是想要单独只授权FFmpegKit，不授权 KSPlayer吗？

**Comment by frestobile** [comment]
https://swiftpackageindex.com/kingslay/FFmpegKit
I am not sure it will work for my project. I need the ffmpeg-kit that supports the AC-4 decoder.
