### ISSUE TITLE
关于编译 FFmpeg 的问题请教

### ISSUE THREAD

**Issue by FaiChou** [kingslay/FFmpegKit#4]
没有研究过这一块，所以有一些问题不明白。

FFmpeg 是一个开源的音视频处理工具集，它用 c 语言写的。

各个平台（Linux/Windows/macOS/tvOS/iOS等）需要编译其源码生成支持对应平台的二进制，以及头文件。这样在项目中就可以通过调用头文件中的函数定义来调用 FFmpeg 里的具体实现。

本项目 FFmpegKit 编写了BuildFFmpeg/main.swift 这个编译规则，它是编译 FFmpeg 的脚本。比如我创建一个 tvOS 平台的项目，项目中引入了 FFmpegKit 这个库，在 Xcode 编译项目的时候，会执行 BuildFFmpeg/main.swift 来进行编译，它会识别编译的平台，如果是 tvOS 则编译出 tvOS，如果是其他平台，则编译出其他平台的产物。

所以上面一段理解有问题吗？是在项目编译时候编译 FFmpeg 么？还是已经编译好了，不用在编译？

如果是在项目编译时候编译 FFmpeg，那使用 swift package manager 导入的 FFmpegKit，哪里的规则让 Xcode 编译项目时候先执行 BuildFFmpeg/main.swift 来进行编译？是 [Package.swift](https://github.com/kingslay/FFmpegKit/blob/d02d22d64662f9c879b8de873e10362efa8d0381/Package.swift#L100) 这里么？那如果是用 CocoaPods 导入的 FFmpeg，那对应的编译规则是在那里？我在 podspec 中没有找到。

**Comment by kingslay** [comment]
已经编译好了，不用在编译了。你们都是直接用这个项目里面生成的xcframework。只有你们需要有对ffmpeg增加不一样的编译参数。才需要自己编译下，产生自己的xcframework。

**Comment by FaiChou** [comment]
哪一个是 FFmpeg 的 xcframework?

**Comment by kingslay** [comment]
"Libavcodec", "Libavfilter", "Libavformat", "Libavutil", "Libswresample", "Libswscale" 这是ffmepg的xcframework。其他是ffmpeg用到的三方xcframework。

**Comment by FaiChou** [comment]
谢谢，我大概明白了。

FFmpeg 编译成很多个 xcframework，也需要添加它所依赖的其他 xcframework。

比如 FFmpeg 编一出的其中一个 `Libavformat.xcframework` 其中包含了各个平台所需要的编译产物，如果项目跑在 tvOS 的模拟器上，则项目编译时候会去找 `tvos-arm64_x86_64-simulator` 这个文件夹下的文件。其中包含 `Libavformat` 二进制文件是 FFmpeg 源码的编译产出，并且还有 Headers 文件夹中暴露的很多方法名。

那为什么 FFmpegKit 项目中还有很多 .h .c 文件？这些文件在项目中起了什么作用？c 语言文件不被编译的话，应该不能被直接调用执行吧？所以这些文件也可以删掉么？

<img width="291" alt="image" src="https://github.com/kingslay/FFmpegKit/assets/18500846/4a48ddb7-6aef-48a3-9bb6-90fa77d7b4e0">

**Comment by kingslay** [comment]
你画出来的这两个是单独的在macos上的运行程序。就是官方的ffplay和ffmpeg。这个是给有人想要学习官方的ffplay代码的话，那就可以用这个来debug运行。

**Comment by FaiChou** [comment]
明白了，它们定义在 executableTarget 中。在工程中编译构建时候会编译这些 c 语言文件生成对应的可执行文件。
