### ISSUE TITLE
这样编译是不是可以支持KSplayer和MPV两套内核

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/FFmpegKit#8]
/// build MPV
swift package --disable-sandbox BuildFFmpeg enable-libdav1d enable-openssl enable-libsrt enable-libfreetype enable-libfribidi enable-harfbuzz enable-libass enable-mpv platforms=ios

我想在播放器里面同时支持两套内核，特定情况下使用MPV播放器。这样编译是不是既提供了ksplayer的依赖支持，又引入了mpv。

**Comment by kingslay** [comment]
是的 你也可以切到分支mpv 里面有编译好的包

**Comment by FantasyKingdom** [comment]
谢谢
